name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: A22051694
          outputs: |
            output/github-contribution-grid-snake.svg

      - name: Commit and Push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "output/github-contribution-grid-snake.svg"
          message: "Generate contribution snake"
